version: "3.8"

services:
  database:
    container_name: bookmark_db
    image: postgres:15.5-alpine
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5435:5432"
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
